language: node_js
node_js:
  - "node"
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database mydiary_test;' -U postgres
befores_script:
  - npm i -D coveralls
script:
  - npm test
after_success:
  - npm run coverage
  - npm run report-coverage
